version: '3.7'

services:
  nginx:
    build: ./services/nginx
    restart: always
    ports:
      - 1337:80
    volumes:
      - media_volume:/home/app/web/tejidos/media
    depends_on:
      - web
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    restart: always
    command: gunicorn --bind 0.0.0.0:5000 tejidos.app:app
    volumes:
      - media_volume:/home/app/web/tejidos/media
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
  worker:
    build: ./services/web
    restart: always
    command: python manage.py run_worker
    volumes:
      - media_volume:/home/app/web/tejidos/media
    environment:
      - IS_WORKER=True
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
  db:
    image: kartoza/postgis:13.0
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  redis:
    restart: always
    image: redis:6-alpine

volumes:
  postgres_data: