version: '3.7'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  worker:
    build: ./services/web
    command: python manage.py run_worker
    volumes:
      - ./services/web/:/usr/src/app/
    environment:
      - IS_WORKER=True
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    image: kartoza/postgis:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
  redis:
    image: redis:6-alpine


volumes:
  postgres_data: